const bannedItems = [
    'actuallyadditions:flax_seeds',
    'actuallyadditions:rice',
    'actuallyadditions:rice_seeds',
    'megacells:cable_mega_emc_interface',
    'megacells:mega_emc_interface',
    'ae2:vibration_chamber',
    'ae2:sky_stone_chest',
    'ae2:smooth_sky_stone_chest',
    'mi_tweaks:eu_transformer',
    'mi_tweaks:flux_transformer',
    'storagedrawers:netherite_storage_upgrade',
    'storagedrawers:diamond_storage_upgrade',
    /modern_industrialization:raw_uranium/,
    /modern_industrialization:\w*uranium_ore/,
    'laserio:laser_connector_advanced',
    'extendedae:silicon_block',
    'extendedae:ex_inscriber',
    'extendedae:ex_charger',
    'projecte:iron_band',
    'industrialforegoing:bioreactor',
    'extended_industrialization:hv_photovoltaic_cell',
    'extended_industrialization:mv_photovoltaic_cell',
    'extended_industrialization:lv_photovoltaic_cell',
    'extended_industrialization:mv_solar_panel',
    'extended_industrialization:hv_solar_panel',
    'extended_industrialization:lv_solar_panel',
    'enderio:soul_engine',
    /aquaculture:\w*fillet_knife/,
    /coxinhautilities:portable/,
    'industrialforegoing:washing_factory',
    'industrialforegoing:fermentation_station',
    'industrialforegoing:fluid_sieving_machine',
    'cursedearth:blessed_flower',
    'cursedearth:blessed_earth',
    'prettypipes:wrench',
    'supplementaries:wrench',
    'enderio:yeta_wrench',
    'enderio:dark_bimetal_gear',
    'enderio:vibrant_gear',
    'ae2:crystal_resonance_generator',
    /actuallyadditions:\w*generator/,
    'enderio:stirling_generator',
    /justhammers:\w*(impact|destructor|reinforced)/,
    'justhammers:stone_hammer',
    'justhammers:netherite_hammer',
    //'modern_industrialization:forge_hammer',
    /modern_industrialization:(diamond|iron|netherite|steel)_hammer/,
    /extended_industrialization:\w*alloy_smelter/,
    'modern_industrialization:bronze_mixer',
    'modern_industrialization:steel_mixer',
    'actuallyadditions:iron_casing',
    /modern_industrialization:\w*water_pump/,
    'industrialforegoing:fluid_extractor',
    //'enderio:primitive_alloy_smelter',
    'ae2:inscriber',
    //'modern_industrialization:wrench',
    'actuallyadditions:wooden_aiot',
    'actuallyadditions:stone_aiot',
    /farmersdelight:\w*knife/,
    'coxinhautilities:fluid_trash_can',
    'coxinhautilities:energy_trash_can',
    `modern_industrialization:chemical_reactor`,
    'productivemetalworks:gear_cast',
    'productivemetalworks:rod_cast',
    'productivemetalworks:plate_cast',
    'coxinhautilities:grannys_sink',
    'productivemetalworks:fire_brick',
    'productivemetalworks:fire_clay',
    `modern_industrialization:iridium_ore`,
   // `modern_industrialization:deepslate_iridium_ore`,
    `modern_industrialization:titanium_ore`,
    `modern_industrialization:tungsten_ore`,
    `modern_industrialization:deepslate_tungsten_ore`,
    'actuallyadditions:laser_relay',
    'actuallyadditions:laser_relay_advanced',
    'actuallyadditions:laser_relay_extreme',
    'modern_industrialization:diesel_mining_drill',
    /modern_industrialization:(coal|diamond|emerald|lapis|lignite_coal|monazite|quartz|redstone|salt)_crushed_dust/,
    /sophisticated\w*:stack_upgrade/,
    'ae2:charger',
    /industrialforegoing:\w*generator/,
    'modularrouters:sender_module_3'
];

bannedItems.forEach(property => {
    ServerEvents.tags('item', e => {
        e.add("c:hidden_from_recipe_viewers", property);
    });

    ServerEvents.recipes(e => {
        e.remove({output: property});
    });

    LootJS.lootTables(e => {
        e.modifyLootTables(LootType.CHEST).removeItem(property)
    });
});